# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SF_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QTime

# for firebase/database
import pyrebase


#*****************************************
class Stream(QtCore.QObject):
    newText = QtCore.pyqtSignal(str)

    def write(self, text):
        self.newText.emit(str(text))
#*****************************************


class Ui_SmartFridge(object):
    def setupUi(self, SmartFridge):
        SmartFridge.setObjectName("SmartFridge")
        SmartFridge.resize(996, 693)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        SmartFridge.setFont(font)
        self.centralwidget = QtWidgets.QWidget(SmartFridge)
        self.centralwidget.setMinimumSize(QtCore.QSize(996, 693))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"gridline-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        
        #Title
        self.title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(255, 211, 47);\n"
"border-radius: 10px;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 1, 0, 1, 1)
        
        #Calender
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("background-color: rgb(254, 177, 31);\n"
"alternate-background-color: rgba(50, 51, 51, 66);\n"
"color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"selection-color: rgba(18, 0, 255, 255);\n"
"selection-background-color: rgb(152, 131, 255);\n"
"border:none;\n"
"border-radius: 15px;")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 8, 1, 1, 1)
        
        #Time
        self.Time = QtWidgets.QLabel(self.frame)

        timer = QTimer(SmartFridge)
        timer.timeout.connect(self.showTime)
        timer.start(1000)

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.Time.setFont(font)
        self.Time.setStyleSheet("background-color: rgb(255, 211, 47);\n"
"border-radius: 10px;")
        self.Time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Time.setIndent(15)
        self.Time.setObjectName("Time")
        self.gridLayout.addWidget(self.Time, 1, 1, 1, 1)
        
        # Add Button
        self.AddItem = QtWidgets.QPushButton(self.frame)
        self.AddItem.clicked.connect(self.AddItemclicked)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setItalic(True)
        self.AddItem.setFont(font)
        self.AddItem.setStyleSheet("\n"
"background-color: rgb(255, 211, 47);\n"
"border: none;\n"
"border-radius: 10px\n"
"\n"
"")
        self.AddItem.setIconSize(QtCore.QSize(12, 12))
        self.AddItem.setObjectName("AddItem")
        self.gridLayout.addWidget(self.AddItem, 13, 1, 1, 1)
        
        #Remove Item
        self.RemoveItem = QtWidgets.QPushButton(self.frame)
        self.RemoveItem.clicked.connect(self.RemoveItemclicked)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setItalic(True)
        self.RemoveItem.setFont(font)
        self.RemoveItem.setStyleSheet("background-color: rgb(255, 211, 47);\n"
"border:none;\n"
"border-radius: 10px;\n"
"")
        self.RemoveItem.setObjectName("RemoveItem")
        self.gridLayout.addWidget(self.RemoveItem, 13, 0, 1, 1)
        
        #Mode
        self.Mode = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Mode.setFont(font)
        self.Mode.setStyleSheet("background-color: rgb(255, 211, 47);\n"
"border-radius: 10px;")
        self.Mode.setAlignment(QtCore.Qt.AlignCenter)
        self.Mode.setObjectName("Mode")
        self.gridLayout.addWidget(self.Mode, 12, 0, 1, 2)
        
        #Table
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 211, 47);\n"
"alternate-background-color: rgba(254, 165, 32, 102);\n"
"border: none;\n"
"border-radius: 10px;")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setAutoScrollMargin(3)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setColumnWidth(0,230)
        self.tableWidget.setColumnWidth(1,230)
        self.loaddata()
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(253, 133, 35))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(253, 133, 35))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidget, 8, 0, 3, 1)
        
        #Status
        self.status = QtWidgets.QTextEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.status.setFont(font)
        self.status.setStyleSheet("background-color: rgb(255, 211, 47);\n"
"border: rgb(255,255,255);\n"
"border-radius: 10px;\n"
"")
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 9, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        SmartFridge.setCentralWidget(self.centralwidget)

        self.retranslateUi(SmartFridge)
        QtCore.QMetaObject.connectSlotsByName(SmartFridge)


        sys.stdout = Stream(newText=self.onUpdateText)

    def onUpdateText(self, text):
        cursor = self.status.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        cursor.insertText(text)
        self.status.setTextCursor(cursor)
        self.status.ensureCursorVisible()

    def __del__(self):
        sys.stdout = sys.__stdout__

    def closeEvent(self, event):
        """Shuts down application on close."""
        # Return standard output to defaults.
        sys.stdout = sys.__stdout__
        super().closeEvent(event)

    def showTime(self):
        currentTime = QTime.currentTime()
        displayText = currentTime.toString("hh : mm : ss")
        self.Time.setText(displayText)

    def AddItemclicked(self):
        self.Mode.setText("Add Item Mode")
        print("Add Item Mode")
        Add = True
        Remove = False

    def RemoveItemclicked(self):
        self.Mode.setText("Remove Item Mode")
        print("Remove Item Mode")
        Add = False
        Remove = True

    def loaddata(self):
        data = []

        firebaseConfig = { 'apiKey': "AIzaSyA2NIKjW9kD31eeRnFDZhpW02q443AoIBA",
        'authDomain': "smart-fridge-94bff.firebaseapp.com",
        'databaseURL': "https://smart-fridge-94bff-default-rtdb.firebaseio.com",
        'projectId': "smart-fridge-94bff",
        'storageBucket': "smart-fridge-94bff.appspot.com",
        'messagingSenderId': "625536633101",
        'appId': "1:625536633101:web:d4951c5cc692fac0364844"
        }
        firebase = pyrebase.initialize_app(firebaseConfig)
        db = firebase.database()
        things = db.child("items").get()

        row = 0
        self.tableWidget.setRowCount(35)

        for things in things.each():
            val = things.val()
            self.tableWidget.setItem(row,0,QtWidgets.QTableWidgetItem(val['Item']))
            self.tableWidget.setItem(row,1,QtWidgets.QTableWidgetItem(val['Weight']))
            row = row+1
    
    def retranslateUi(self, SmartFridge):
        _translate = QtCore.QCoreApplication.translate
        SmartFridge.setWindowTitle(_translate("SmartFridge", "Smart Fridge"))
        self.title.setText(_translate("SmartFridge", "SMART FRIDGE"))
        #self.Time.setText(_translate("SmartFridge", "Time"))
        self.AddItem.setText(_translate("SmartFridge", "ADD \n"
"ITEM"))
        self.RemoveItem.setText(_translate("SmartFridge", "REMOVE \n"
"ITEM"))
        self.Mode.setText(_translate("SmartFridge", "Add Item Mode"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SmartFridge", "Item Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SmartFridge", "Weight (in grams)"))

    def print(self):
        print("Updating!!")
        print("Ready!")


if __name__ == "__main__":
    Add = True
    Remove = False
    print("Updating !!")
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SmartFridge = QtWidgets.QMainWindow()
    print("Ready!")


    ui = Ui_SmartFridge()
    ui.setupUi(SmartFridge)
    SmartFridge.show()
    sys.exit(app.exec_())
